#!/usr/bin/env python3
"""Generate the Claude Code role-agent bodies from SWARM.md "Role duties".

SWARM.md is the only hand-edited home of each role's duties (CLAUDE.md: one
fact, one home). Claude launches roles from `~/.claude/agents/qsim-ROLE.md`,
whose body lands in the agent's system prompt, so the duty text must also be
there. This script copies it: each body is a short Claude-specific header plus
the `every` block and the role's block, delimited in SWARM.md by
`<!-- role:NAME -->` ... `<!-- /role -->`. Frontmatter (model, tools, skills,
guard hooks) is preserved byte for byte and never generated.

    uv run python tools/gen_role_bodies.py            # rewrite the agent bodies
    uv run python tools/gen_role_bodies.py --check    # exit 1 if any body is stale
    uv run python tools/gen_role_bodies.py --out DIR  # write to DIR for review

The agent files live outside the repository. When the agents directory or a
role file is absent (another machine, Codex-only host), --check reports
"skipped" and exits 0: there is nothing to keep current there.
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
ROLES = ("deriver", "surveyor", "falsifier", "referee")
BLOCK = re.compile(r"<!-- role:(\w+) -->\n(.*?)\n<!-- /role -->", re.S)

HEADER = """<!-- GENERATED by {root}/tools/gen_role_bodies.py from SWARM.md "Role duties".
     Do not edit this body: edit SWARM.md and regenerate. Frontmatter is kept as is. -->
You are the **{role}** in a QSim research swarm running under Claude Code. Your
preloaded skills are `qsim-research` (the research workflow) and `qsim-worker`
(Claude board mechanics). Read the research root's `CLAUDE.md`, `METHOD.md` and
`SWARM.md` first. A PreToolUse guard (`worker_guard.py --role {role}`) refuses
writes outside {writes} and the session scratchpad; it is lexical, not a
sandbox, so programs you run must write only there too. This host may refuse
`.md` files written by a subagent; then use `.txt` and the submission summary.

The duties below are copied from `SWARM.md` "Role duties (host-neutral)" and bind.

"""
WRITES = {"referee": "`out/agent-board/reviews/`"}


def blocks(swarm_text: str) -> dict[str, str]:
    found = {name: body.strip() for name, body in BLOCK.findall(swarm_text)}
    missing = [r for r in ("every", *ROLES) if r not in found]
    if missing:
        raise SystemExit(f"SWARM.md lacks role blocks: {', '.join(missing)}")
    return found


def frontmatter(text: str) -> str:
    m = re.match(r"---\n.*?\n---\n", text, re.S)
    if not m:
        raise SystemExit("agent file has no frontmatter")
    return m.group(0)


def body_for(role: str, found: dict[str, str]) -> str:
    header = HEADER.format(root=ROOT, role=role,
                           writes=WRITES.get(role, "`out/agent-board/workers/`"))
    return header + found["every"] + "\n\n" + found[role] + "\n"


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--swarm", type=Path, default=ROOT / "SWARM.md")
    ap.add_argument("--agents-dir", type=Path, default=Path.home() / ".claude" / "agents")
    mode = ap.add_mutually_exclusive_group()
    mode.add_argument("--check", action="store_true")
    mode.add_argument("--out", type=Path)
    ns = ap.parse_args(argv)
    found = blocks(ns.swarm.read_text())
    stale, skipped = [], []
    for role in ROLES:
        src = ns.agents_dir / f"qsim-{role}.md"
        if not src.is_file():
            skipped.append(role)
            continue
        current = src.read_text()
        wanted = frontmatter(current) + body_for(role, found)
        if ns.check:
            if current != wanted:
                stale.append(str(src))
        elif ns.out:
            ns.out.mkdir(parents=True, exist_ok=True)
            (ns.out / src.name).write_text(wanted)
        elif current != wanted:
            src.write_text(wanted)
            print(f"wrote {src}")
    if skipped:
        print(f"skipped (no agent file): {', '.join(skipped)}")
    if stale:
        print("stale role bodies; run uv run python tools/gen_role_bodies.py:")
        for s in stale:
            print(f"  {s}")
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
