"""Regenerate every INDEX.md, and CLAIMS.md, from frontmatter.

These outputs are DERIVED. Never hand-edit them -- a hand-maintained mirror is
the failure mode this layout exists to remove (see RESTRUCTURE.md).

    uv run python tools/reindex.py            # write
    uv run python tools/reindex.py --check    # exit 1 if anything is stale

`check.py` calls this with --check, so a stale index fails the gate.
"""
from __future__ import annotations

import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent

BANNER = "<!-- GENERATED by tools/reindex.py -- do not edit by hand -->"


def parse(path: pathlib.Path) -> tuple[dict, str]:
    """Minimal YAML-ish frontmatter reader. Values are strings or [a, b] lists."""
    text = path.read_text()
    if not text.startswith("---\n"):
        return {}, text
    _, fm, body = text.split("---\n", 2)
    meta: dict[str, object] = {}
    key = None
    for line in fm.split("\n"):
        if not line.strip():
            continue
        if line.startswith((" ", "\t")) and key:  # folded continuation
            meta[key] = f"{meta[key]} {line.strip()}".strip()
            continue
        if ":" not in line:
            continue
        key, _, val = line.partition(":")
        key, val = key.strip(), val.strip()
        if val.startswith("[") and val.endswith("]"):
            inner = val[1:-1].strip()
            meta[key] = [v.strip() for v in inner.split(",") if v.strip()]
        elif val in (">", "|"):
            meta[key] = ""
        else:
            if len(val) > 1 and val[0] == val[-1] == '"':
                val = val[1:-1].replace('\\"', '"').replace("\\\\", "\\")
            meta[key] = val
    return meta, body


def load(d: pathlib.Path) -> list[tuple[dict, pathlib.Path]]:
    out = []
    for p in sorted(d.rglob("*.md")):
        if p.name == "INDEX.md" or p.name.startswith("_"):
            continue  # _-prefixed files are prose, not records
        meta, _ = parse(p)
        if meta:
            out.append((meta, p))
    return out


def claim_key(meta: dict) -> tuple:
    i = str(meta.get("id", ""))
    return (i[0] if i else "z", int(i[1:]) if i[1:].isdigit() else 999, i)


def todo_key(meta: dict) -> tuple:
    i = str(meta.get("id", ""))
    if i.startswith("hk"):
        return (2, int(i[2:] or 0), "")
    num = "".join(c for c in i if c.isdigit())
    suf = "".join(c for c in i if c.isalpha())
    return (1, int(num or 0), suf)


def rel(p: pathlib.Path) -> str:
    return p.relative_to(ROOT).as_posix()


# --------------------------------------------------------------------------


def build_claims_index() -> str:
    rows = load(ROOT / "claims")
    live = sorted((m for m, p in rows if m.get("status") != "retracted"), key=claim_key)
    dead = sorted((m for m, p in rows if m.get("status") == "retracted"), key=claim_key)
    paths = {str(m.get("id")): p for m, p in rows}
    L = [
        BANNER,
        "",
        "# Claims index",
        "",
        "One claim per file in `claims/`. This table is generated from their",
        "frontmatter; the claim file is the single source of truth for its own",
        "status. Retracted claims are in `claims/retracted/` and **may not be",
        "cited as support**.",
        "",
        f"**{len(live)} live · {len(dead)} retracted**",
        "",
        "## Live",
        "",
        "| id | paper | status | claim |",
        "|---|---|---|---|",
    ]
    for m in live:
        i = str(m.get("id"))
        L.append(
            f"| [{i}]({rel(paths[i])}) | {m.get('paper','-')} | {m.get('status','-')} "
            f"| {str(m.get('one_line','')).strip()} |"
        )
    L += ["", "## Retracted / dead — do not cite as support", "",
          "| id | status | claim |", "|---|---|---|"]
    for m in dead:
        i = str(m.get("id"))
        L.append(f"| [{i}]({rel(paths[i])}) | {m.get('killed_by','retracted')} "
                 f"| {str(m.get('one_line','')).strip()} |")
    return "\n".join(L) + "\n"


def build_notes_index() -> str:
    rows = sorted(load(ROOT / "notes"), key=lambda r: str(r[0].get("code", "")))
    L = [
        BANNER, "", "# Notes index", "",
        "One investigation per file. These are the **historical working record**:",
        "they say what was believed at the time, so a note may contain a status",
        "later superseded. Where a note disagrees with a claim file, the claim",
        "file wins.", "",
        f"**{len(rows)} investigations**", "",
        "| code | date | outcome | subject | claims |",
        "|---|---|---|---|---|",
    ]
    for m, p in rows:
        cl = m.get("claims") or []
        L.append(
            f"| [{m.get('code','-')}]({rel(p)}) | {m.get('date','-')} "
            f"| {m.get('outcome','-')} | {str(m.get('title','')).strip()} "
            f"| {', '.join(cl) if cl else '-'} |"
        )
    return "\n".join(L) + "\n"


def build_todo_index() -> str:
    rows = load(ROOT / "todo")
    op = sorted((r for r in rows if r[0].get("state") == "open"), key=lambda r: todo_key(r[0]))
    dn = sorted((r for r in rows if r[0].get("state") != "open"), key=lambda r: todo_key(r[0]))
    L = [
        BANNER, "", "# TODO index", "",
        "One item per file. State is the directory it lives in: moving a file",
        "between `open/` and `done/` is how state changes.", "",
        f"**{len(op)} open · {len(dn)} done**", "",
        "## Open", "", "| id | item |", "|---|---|",
    ]
    for m, p in op:
        L.append(f"| [{m.get('id')}]({rel(p)}) | {str(m.get('title','')).strip()} |")
    L += ["", "## Done", "", "| id | item | outcome |", "|---|---|---|"]
    for m, p in dn:
        L.append(f"| [{m.get('id')}]({rel(p)}) | {str(m.get('title','')).strip()} "
                 f"| {str(m.get('outcome','')).strip() or '-'} |")
    return "\n".join(L) + "\n"


def build_claims_aggregate() -> str:
    """CLAIMS.md, kept as a generated aggregate because both papers cite it as
    supplementary material."""
    rows = load(ROOT / "claims")
    live = sorted((r for r in rows if r[0].get("status") != "retracted"), key=lambda r: claim_key(r[0]))
    dead = sorted((r for r in rows if r[0].get("status") == "retracted"), key=lambda r: claim_key(r[0]))
    L = [
        BANNER, "", "# Claims ledger — generated aggregate", "",
        "**This file is GENERATED from `claims/*.md` by `tools/reindex.py`.**",
        "Edit the individual claim file, not this. It exists so the papers can",
        "ship one self-contained supplementary document.", "",
        f"{len(live)} live claims, {len(dead)} retracted.", "",
    ]
    for m, p in live:
        _, body = parse(p)
        L += [f"---", "", f"## {m.get('id')} — {str(m.get('one_line','')).strip()}", "",
              f"*status: {m.get('status','-')} · paper: {m.get('paper','-')}*", "",
              body.strip(), ""]
    L += ["---", "", "# Retracted / dead", "",
          "**Nothing in this section may be cited as support.** Kept so a fresh",
          "session does not re-derive it.", ""]
    for m, p in dead:
        _, body = parse(p)
        L += [f"---", "", f"## {m.get('id')} — {str(m.get('one_line','')).strip()}", "",
              f"*killed by: {m.get('killed_by','-')}*", "", body.strip(), ""]
    return "\n".join(L) + "\n"


def build_notes_aggregate() -> str:
    """NOTES.md, kept as a generated aggregate. Around a hundred references to
    it survive in claim files, historical experiment scripts and METHOD.md;
    regenerating is cheaper and safer than rewriting those, and the experiment
    scripts are records that should not be edited at all. The hot path is
    notes/INDEX.md -- nobody needs to read this."""
    rows = sorted(load(ROOT / "notes"), key=lambda r: str(r[0].get("code", "")))
    pre = ROOT / "notes" / "_preamble.md"
    L = [BANNER, "", "# PPS / Shor working notes — generated aggregate", "",
         "**GENERATED from `notes/*.md` by `tools/reindex.py`.** Edit the",
         "individual note, not this. It exists so that existing `NOTES.md §CODE`",
         "references keep resolving.", ""]
    if pre.exists():
        L += [parse(pre)[1].strip(), ""]
    for m, p in rows:
        _, body = parse(p)
        L += ["---", "", body.strip(), ""]
    return "\n".join(L) + "\n"


TARGETS = [
    (ROOT / "todo" / "INDEX.md", build_todo_index, ROOT / "todo"),
    (ROOT / "claims" / "INDEX.md", build_claims_index, ROOT / "claims"),
    (ROOT / "notes" / "INDEX.md", build_notes_index, ROOT / "notes"),
    (ROOT / "CLAIMS.md", build_claims_aggregate, ROOT / "claims"),
    (ROOT / "NOTES.md", build_notes_aggregate, ROOT / "notes"),
]


def main(argv: list[str]) -> int:
    check = "--check" in argv
    stale, wrote = [], []
    for path, build, needs in TARGETS:
        if not needs.exists():
            continue
        want = build()
        have = path.read_text() if path.exists() else None
        if have == want:
            continue
        if check:
            stale.append(path)
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(want)
            wrote.append(path)
    if check:
        if stale:
            print("STALE (run: uv run python tools/reindex.py)")
            for p in stale:
                print(f"  {rel(p)}")
            return 1
        print("indexes up to date")
        return 0
    for p in wrote:
        print(f"  wrote {rel(p)}")
    if not wrote:
        print("  (nothing to do)")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
